"""empty message

Revision ID: 7ebf95a239fa
Revises: 4dd1575ca010
Create Date: 2021-06-12 17:21:24.547347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebf95a239fa'
down_revision = '4dd1575ca010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_date21', sa.String(length=50), nullable=True))
        batch_op.alter_column('register_date',
               existing_type=sa.TEXT(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('register_date',
               existing_type=sa.TEXT(length=100),
               nullable=False)
        batch_op.drop_column('register_date21')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
