"""Added flight price

Revision ID: d228cbc3ad4e
Revises: 01cd45f9b550
Create Date: 2021-08-23 16:41:32.508176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd228cbc3ad4e'
down_revision = '01cd45f9b550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_price', sa.Integer(), nullable=False))
        batch_op.alter_column('departure_time',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('arrive_time',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('flight_class',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('flight_class',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('arrive_time',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('departure_time',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('flight_price')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
