"""empty message

Revision ID: f842b9d8630b
Revises: 
Create Date: 2021-06-12 17:16:21.725219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f842b9d8630b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('address')
        batch_op.drop_column('register_date12')
        batch_op.drop_column('address2')
        batch_op.drop_column('address3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address3', sa.TEXT(length=100), nullable=True))
        batch_op.add_column(sa.Column('address2', sa.TEXT(length=100), nullable=True))
        batch_op.add_column(sa.Column('register_date12', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(length=100), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
